version: '2'
services:
    apiservice-mongodb:
        container_name: apiservice-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        command: mongos --configdb apiservice-mongodb-config
    apiservice-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    apiservice-mongodb-config:
        image: mongo:3.2.10
        container_name: apiservice-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
