version: '2'
services:
    apiservice-mongodb:
        container_name: apiservice-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/apiservice/mongodb/:/data/db/
