version: '2'
services:
    auth-mongodb:
        container_name: auth-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/auth/mongodb/:/data/db/
