version: '2'
services:
    apimanageservice-mongodb:
        container_name: apimanageservice-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/apimanageservice/mongodb/:/data/db/
