version: '2'
services:
    jenkinsservice-mongodb:
        container_name: jenkinsservice-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/jenkinsservice/mongodb/:/data/db/
