version: '2'
services:
    jenkinsservice-mongodb:
        container_name: jenkinsservice-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        command: mongos --configdb jenkinsservice-mongodb-config
    jenkinsservice-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    jenkinsservice-mongodb-config:
        image: mongo:3.2.10
        container_name: jenkinsservice-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
