version: '2'
services:
    onepass-mongodb:
        container_name: onepass-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        command: mongos --configdb onepass-mongodb-config
    onepass-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    onepass-mongodb-config:
        image: mongo:3.2.10
        container_name: onepass-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
