version: '2'
services:
    onepass-mongodb:
        container_name: onepass-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/onepass/mongodb/:/data/db/
